name:                steno
version:             0.1.0.0
github:              "LuukBerkers/steno"
license:             GPL-3.0-or-later
author:              "Luuk Berkers"
copyright:           "2022 Luuk Berkers"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/steno#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  steno-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - steno

tests:
  steno-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - steno
